### PR TITLE
German translation for ClimatesOfFerngill

### PR DESCRIPTION
**Pull request by jahangmar**
adds de.json and fixes a typo in default.json

### CODE REVIEW

**Comment by Sakorona** [comment]
Thanks! How do you want to be credited?

**Comment by jahangmar** [comment]
I credit people that make translations for my mods by putting their names in the changelog and in the description so something similar would make me happy as long as my name appears at least somewhere.

**Comment by Sakorona** [comment]
Got it. I've added you to the changelog and description, and when I upload 1.5.3 on Saturday it'll be sync'd to the Nexus.

**Comment by Sakorona** [comment]
As a note, with 1.5.4, there's a new line added to the description:

  "weather-tv.rain.unknown": "showers",

**Pull request merged**
